project:
  type: website
  output-dir: docs

website:
  title: "testsite"
  navbar:
    background: "#efefef"
    left:
      - href: index.qmd
        text: Home
      - webtool.qmd

format:
  html:
    theme: Yeti
    mainfont: sorts mill gordy
    fontsize: 1.5rem
    fontcolor: "#1c2120"
    linkcolor: "#989430"
    monofont: courier new
    css: styles.css
    toc: true



